version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
    - echo Start build on `date`
  build:
    commands:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    - for d in */ ; do npm --prefix ./$d i ./$d; done
  post_build:
    commands:
    - echo Build completed on `date`

artifacts:
  files:
  - '**/*'
  discard-paths: no
