version: 0.2

phases:
  pre_build:
    commands:
    - BUCKET=deutschebank
    - aws --version
    - pip install --upgrade pip
    - pip install aws-sam-cli
    - pip install botocore==1.10.82
    - sam --version
  build:
    commands:
    - sam validate
    - sam package --template-file template.yaml --s3-bucket $BUCKET --output-template-file packaged.yaml
    - sam deploy --template-file ./packaged.yaml --stack-name deutschebankApi --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
    - REST_API_ID=3en7nrlhm7
    - aws apigateway put-rest-api --rest-api-id $REST_API_ID --mode overwrite --body file://openapi-apigateway.yaml
    - aws apigateway create-deployment --rest-api-id $REST_API_ID --stage-name Stage
  post_build:
    commands:
    - echo Deployment is done!
